# Database name: pw_manager
# Charset : UTF-8
# User : mediado
# Password: pengin

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
ID VARCHAR(255) NOT NULL PRIMARY KEY,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ACTIVE BOOLEAN DEFAULT FALSE NOT NULL,
CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
UPDATE_AT DATETIME
);

ALTER TABLE USER ADD UNIQUE(EMAIL);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT(
ID VARCHAR(255) NOT NULL PRIMARY KEY,
USER_ID VARCHAR(255) NOT NULL,
URL VARCHAR(255) NOT NULL,
ACCOUNT_NAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
UPDATE_AT DATETIME
);

DROP TABLE IF EXISTS SEQUENCE;
CREATE TABLE SEQUENCE (
TABLE_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
SEQUENCE_NUMBER DOUBLE DEFAULT 0 NOT NULL,
CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
UPDATE_AT DATETIME
);