# Database name: pw_manager
# Charset : UTF-8
# User : mediado
# Password: pengin

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
ID MEDIUMINT AUTO_INCREMENT,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ACTIVE BOOLEAN DEFAULT FALSE,
CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATE_AT DATETIME,
PRIMARY KEY(ID)

);
ALTER TABLE USER ADD UNIQUE(EMAIL);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT(
ID MEDIUMINT AUTO_INCREMENT,
USER_ID VARCHAR(255) NOT NULL,
URL VARCHAR(255) NOT NULL,
ACCOUNT_NAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATE_AT DATETIME,
PRIMARY KEY(ID)
);